// Generated by https://quicktype.io

export interface Patient {
    patientId:        number;
    name:             string;
    surname:          string;
    dateOfBirth:      string;
    phoneNumber:      string;
    address:          string;
    email:            string;
    emergencyContact: string;
    medicalInsurance: string;
}
