// Generated by https://quicktype.io

export interface Vital {
    vitalsId:        number;
    patientId:       number;
    height:          number;
    weight:          number;
    respiratoryRate: number;
    bloodPressure:   string;
    heartRate:       string;
    dateTaken:       string;
}
