// Generated by https://quicktype.io

export interface Consultation {
    consultationId:        number;
    patientId:             number;
    reasonForConsultation: string;
    physicalExam:          string;
    nameOfDiagnosis:       string;
    categoryOfDiagnosis:   string;
    medicalPrescription:   string;
    medicalInstructions:   string;
    consultationDate:      string;
    dateOfNextVisit:       string;
}
